var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fbwztr._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0-firay.js")
R.c("server/chunks/ssr/[root-of-the-server]__06bmssn._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ucemvw._.js")
R.c("server/chunks/ssr/src_0orsyc~._.js")
R.c("server/chunks/ssr/src_app_error_tsx_0oqfei_._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_login_page_actions_02kefem.js")
R.m(78157)
module.exports=R.m(78157).exports
